---
- name: Unmount points
  mount:
    path: "{{ item.path }}"
    state: unmounted
  become: true
  with_items:
    - "{{ app_volumes }}"

- name: Clean mount points
  mount:
    path: "{{ item.path }}"
    state: absent
  become: true
  with_items:
    - "{{ app_volumes }}"

- name: Clean logical volumes
  lvol:
    vg: "{{ item.vg }}"
    lv: "{{ item.lv }}"
    force: true
    state: absent
  become: true
  with_items:
    - "{{ app_volumes }}"

- name: Clean application folders
  file:
    name: "{{ item.path }}"
    state: absent
  become: true
  with_items:
    - "{{ app_volumes }}"
